### ISSUE TITLE
Bundle not working on "old" mac version

### ISSUE THREAD

**Issue by sjalex78** [saramic/qrtc.art#1]
Running Bundle in the command line to update libraries and had the current response

"Unable to find a spec satisfying nokogiri (>= 1.8.5) in the set. Perhaps the lockfile is
corrupted? Found nokogiri (1.11.7-x86_64-linux), nokogiri (1.11.7-arm64-darwin) that did
not match the current platform."

**Comment by saramic** [comment]
hmm, I might try

```
bundle lock --add-platform x86_64-darwin
```

pull push now see if it works

**Comment by sjalex78** [comment]
hmmm, now has worked with your update inclusion. 

Thanks
