### ISSUE TITLE
Hugo Theme for QRTC blog

### ISSUE THREAD

**Issue by sjalex78** [saramic/qrtc.art#2]
[https://demo.gethugothemes.com/touchy/?_gl=1*ccjogg*_ga*MTgxMzUyNjI5OC4xNjMyMzAyMjI0*_ga_XZDZ72MZWW*MTYzMjMwMjIyNC4xLjAuMTYzMjMwMjIyNS4w&_ga=2.150516464.737835334.1632302225-1813526298.1632302224]

[https://gethugothemes.com/products/touchy/]

**Comment by saramic** [comment]
added in https://github.com/saramic/blog.qrtc.art
